"""
RoadWise — FastAPI Backend
---------------------------
This is the "middleman" between the React frontend and the AI agents.

Endpoints:
  POST /api/chat       — main chat endpoint (intake phase + planning phase)
  GET  /api/health     — health check
  DELETE /api/session/{id} — clear a session

The app maintains in-memory conversation sessions. Each browser tab gets
a unique session_id (UUID generated by the frontend).
"""

import json
import re
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from agents import Runner, set_default_openai_key

from config import OPENAI_API_KEY
from schemas.trip import ChatRequest, ChatResponse, TripBrief, VehicleInfo
from app_agents.intake_agent import create_intake_agent
from app_agents.route_agent import create_route_agent
from app_agents.experience_agent import create_experience_agent
from app_agents.orchestrator import run_orchestrator

# Set the API key for the openai-agents SDK (works with openai>=2.x)
set_default_openai_key(OPENAI_API_KEY)

# ── In-memory session store ──────────────────────────────────────────────────
# Structure: { session_id: { "history": [...], "phase": "intake"|"planning"|"done", "plan": TripPlan|None } }
sessions: dict = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup/shutdown logic."""
    print("✅ RoadWise backend starting up")
    yield
    print("🛑 RoadWise backend shutting down")


app = FastAPI(
    title="RoadWise API",
    description="Road trip planning powered by multi-agent AI",
    version="1.0.0",
    lifespan=lifespan,
)

# Allow the React dev server (port 5173) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/api/health")
async def health():
    return {"status": "ok", "service": "RoadWise"}


@app.delete("/api/session/{session_id}")
async def clear_session(session_id: str):
    sessions.pop(session_id, None)
    return {"cleared": True}


@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    session_id = request.session_id
    user_message = request.message.strip()

    if not user_message:
        raise HTTPException(status_code=400, detail="Message cannot be empty.")

    # Initialize session if new
    if session_id not in sessions:
        sessions[session_id] = {
            "history": [],
            "phase": "intake",
            "plan": None,
        }

    session = sessions[session_id]

    # ── PHASE: intake ────────────────────────────────────────────────────────
    if session["phase"] == "intake":
        # Append user message to history
        session["history"].append({"role": "user", "content": user_message})

        # Run the Intake Agent with full conversation history
        intake_agent = create_intake_agent()
        result = await Runner.run(
            intake_agent,
            input=session["history"],
        )
        reply = result.final_output

        # Append assistant reply to history
        session["history"].append({"role": "assistant", "content": reply})

        # Check if the agent has emitted the completion JSON block
        trip_brief = _parse_trip_brief(reply)

        if trip_brief:
            # Strip the JSON block from what we show the user
            display_reply = reply.split("TRIP_BRIEF_JSON:")[0].strip()
            session["phase"] = "planning"

            # ── PHASE: planning — run the orchestrator pipeline ──────────────
            try:
                route_agent = create_route_agent()
                experience_agent = create_experience_agent()
                plan = await run_orchestrator(trip_brief, route_agent, experience_agent)

                session["plan"] = plan
                session["phase"] = "done"

                return ChatResponse(
                    session_id=session_id,
                    reply=display_reply,
                    trip_plan=plan,
                    phase="done",
                )
            except Exception as e:
                # Surface planning errors gracefully to the user
                session["phase"] = "intake"  # let them retry
                return ChatResponse(
                    session_id=session_id,
                    reply=(
                        f"{display_reply}\n\n"
                        f"⚠️ I hit a snag while building your plan: {str(e)}. "
                        "Let's try again — could you re-confirm your trip details?"
                    ),
                    phase="intake",
                )

        # Still in intake — return the agent's question/response
        return ChatResponse(
            session_id=session_id,
            reply=reply,
            phase="intake",
        )

    # ── PHASE: done (plan already exists) ───────────────────────────────────
    if session["phase"] == "done":
        # User might ask follow-up questions about their plan
        return ChatResponse(
            session_id=session_id,
            reply=(
                "Your trip plan is ready above! 🗺️ "
                "If you'd like to plan a different trip, click **New Trip** to start over."
            ),
            trip_plan=session["plan"],
            phase="done",
        )

    raise HTTPException(status_code=500, detail="Unknown session state.")


# ── Helpers ──────────────────────────────────────────────────────────────────

def _parse_trip_brief(text: str) -> TripBrief | None:
    """
    Look for the TRIP_BRIEF_JSON: marker in the agent's response.
    If found and valid, return a TripBrief object. Otherwise return None.
    """
    if "TRIP_BRIEF_JSON:" not in text:
        return None

    try:
        json_part = text.split("TRIP_BRIEF_JSON:", 1)[1].strip()
        # Extract the JSON object
        match = re.search(r"\{[\s\S]*\}", json_part)
        if not match:
            return None

        data = json.loads(match.group())
        vehicle_data = data.pop("vehicle", {})
        vehicle = VehicleInfo(**vehicle_data)
        return TripBrief(vehicle=vehicle, **data)

    except Exception:
        return None
